spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "526155795442-rbem6s5u0b4ujdqs9doqhu614vrgd5f4.apps.googleusercontent.com"
            client-secret: "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"