spring:
  datasource:
    url: jdbc:postgresql://podofarm-rds-instance.cdo2amggo1em.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: pfadmin
    password: podofarm8848
    driver-class-name: org.postgresql.Driver


  thymeleaf:
    prefix: classpath:/templates/

  security:
    oauth2:
      client:
        registration:
          google:

application:
  version: 1.0.0
