spring:
  datasource:
    url: jdbc:postgresql://mildo-rds-instance2.cdo2amggo1em.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: mildoadmin
    password: mildo8848
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    prefix: classpath:/templates/

  security:
    oauth2:
      client:
        registration:
          google:

  config:
    import: application-secret.yml

application:
  version: 1.0.0

server:
  port: 8080




