spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "16499342854-6r9g5vts2ivorfub6e6hothno6hb8kue.apps.googleusercontent.com"
            client-secret: "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"
#            redirect-uri: "https://api.podofarm.xyz/login/oauth2/code/google"
            redirect-uri: "https://api.mildo.xyz/login/oauth2/code/google"
            scope: profile, email, openid
            authorization-grant-type: authorization_code
            client-name: Google



